---
title: "making-worklog-db"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{making-worklog-db}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(worklog)
```

Create the work log DB

```{r}
tmp_file <- tempfile(fileext = ".db")
create_worklog(tmp_file)
```

# Add information

```{r}
  add_contact(
    title = "Dr",
    firstname = "Robin",
    surname = "Smit",
    fullname = "Robin Smit",
    other_info = list(
      nickname = "Robin",
      notes = "Working with for a long time"
    ),
    db = tmp_file
  )
  add_client(
    name = "TER",
    short_name = "TER",
    long_name = "Transport Emission Research",
    other_info = list(
      notes = "Robin's company"
    ),
    db = tmp_file
  )
  add_position(
    client_id = 1,
    contact_id = 1,
    name = "Director",
    start_date = Sys.Date(),
    end_date = Sys.Date(),
    db = tmp_file
  )
  add_address(
    contact_id = 1,
    position_id = 1,
    type = "email",
    value = "fake@fakemails.com",
    db = tmp_file
  )
```

# Write out to Excel:

```{r}
tmp_xlsx_file <- tempfile(fileext = ".xlsx")
create_xlsx_from_db(
  path = tmp_xlsx_file,
  db = tmp_file
)
```

